services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: QuestHub-Frontend
    ports:
      - "4173:4173"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
      - /app/dist
    environment:
      - VITE_API_URL=http://QuestHub-APIGateway:8000/auth/
  
  api-gateway:
    build:
      context: ./APIGateway
      dockerfile: Dockerfile
    container_name: QuestHub-APIGateway
    ports:
      - "3000:3000"
    environment:
      - AUTH_SERVICE_URL=http://QuestHub-Auth:8000/auth/
      - JWT_PUBLIC_KEY=/Secrets/public.key
    volumes:
      - ./APIGateway:/app
      - ./Secrets:/Secrets:ro
    depends_on:
      - auth-service

  auth-service:
    build:
      context: ./Services/Auth
      dockerfile: Dockerfile
    container_name: QuestHub-Auth
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=/Secrets/DJANGO_SECRET_KEY.key
      - JWT_PRIVATE_KEY=/Secrets/private.key
      - JWT_PUBLIC_KEY=/Secrets/public.key
    volumes:
      - ./Services/Auth:/app
      - ./Secrets:/Secrets:ro
    depends_on:
      AuthDB:
        condition: service_healthy
          
  AuthDB:
    image: mysql
    container_name: QuestHub-AuthDB
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: QuestHubAuth
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - ./DB/AuthDB:/var/lib/mysql
    healthcheck:
     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
     interval: 10s
     timeout: 5s
     retries: 5

  post-service:
    build:
      context: ./Services/Post
      dockerfile: Dockerfile
    container_name: QuestHub-Post
    ports:
      - "8001:8001"
    environment:
      - POST_DATABASE_URL=mongodb://QuestHub-PostDB:27017/QuestHub-Post
    volumes:
      - ./Services/Post:/app
  
  PostDB:
    image: mongo
    container_name: QuestHub-PostDB
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./DB/PostDB:/data/db